language: php

php:
  - 5.4
  - 5.5

install:
  - composer install --prefer-source --dev --no-interaction

script:
  - mkdir -p build/logs
  - bin/phpunit -c phpunit_ci.xml

after_script:
  - bin/coveralls -v

branches:
  only:
    - /^worker-.+$/
    - /^.+-worker$/
